name: 'test-every-push'
on:
  push:
    branches:
      - 'master'
jobs:
  deploy:
    name: 쿠버네티스 배포
    runs-on: ubuntu-latest
    needs: [docker, tag]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - run: kubectl get all
